### ISSUE TITLE
cover.set_cover_position

### ISSUE THREAD

**Issue by johination** [davidramosweb/home-assistant-custom-components-cover-time-based#4]
the covers can only be opened completely or completely.
I remember in an earlier version of the Home Assistant you could still set the slider

**Comment by davidramosweb** [comment]
Hi,
What version of home assistant do you have? I see the slider on the panel
![image](https://user-images.githubusercontent.com/4605169/96637845-8dde4480-131f-11eb-8320-ee19a5fe203a.png)
