### ISSUE TITLE
Monitor physical sw state

### ISSUE THREAD

**Issue by nunofmds** [davidramosweb/home-assistant-custom-components-cover-time-based#5]
Hi,

Is it possible to track/monitor the physical sw? When the SW button is pressed nothing happens on the entity so it does not record the real position of the blinds...

Regards,
Nuno

**Comment by davidramosweb** [comment]
Hi
The only thing you can do is unlink the physical button from the relay if it allows it and make an automation when the button is pressed obtaining the event with the development tools in home assistant.
:)

**Comment by nunofmds** [comment]
huummm... i will try to go with other options then... thanks!
